/*
 * This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. 
 * http://creativecommons.org/licenses/by-nc/3.0/
 */
package ChatAddress;

/**
 *
 * @author Edgar, Sara, Andre
 */
public class Cake extends javax.swing.JFrame {

    /**
     * Creates new form Cookie
     */
    public Cake() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("ChatAddress");

        jLabel2.setText("Chat Address is a software published by Team Husky.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Developers:");

        jLabel4.setText("Sara Tenkanen - https://github.com/tenkanen");

        jLabel5.setText("Edgar Axelsson - https://github.com/edgaraxe");

        jLabel6.setText("Andre Gonzalez - https://github.com/latonido");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("License:");

        jLabel9.setText("This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(75, 75, 75)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cake().setVisible(true);
            }
        });

        /**
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM$  .$.        .MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM$    .ONNNN.          .NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM       .NNNNNN.            7MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMM         .NNNNNNNN.            ?MMMMMMMMMMMMMM
MMMMMMMMMMMM           .NNNNNNNNNN..           MMMMMMMMMMMMM
MMMMMMMMMMM            .NNNNNNNNNNNNNNNN.       .MMMMMMMMMMM
MMMMMMMMM.              INNNNNNNNNNNNNNNNN$I..   .MMMMMMMMMM
MMMMMMMM                 ~NNNNNNNNNNNNNNNNNN$.     MMMMMMMMM
MMMMMMMZ                  .NNNNNNNNNNNNNNNNNNN8I    MMMMMMMM
MMMMMMM            .+.?.   7NNNNNNNNNNNNNNNNNNNN+.. MMMMMMMM
MMMMMM.            NNN=... .NNNNNNNNNNNNNNNNNNNNNND,.MMMMMMM
MMMMMM             NNNNNNNN:NNNNNNNNNNNNNNNNNNNNNNNN.MMMMMMM
MMMMM.             8NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.MMMMMM
MMMMM               .8NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN.MMMMMM
MMMMM                 ..NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMM
MMMMM.                   .NNNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMM
MMMMM                     .NNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMM
MMMMM                      $NNNNNNNNNNNNNNNNNNNNNNNNN.MMMMMM
MMMMM.  NNNNNNND .N. NN..N. NN.N.N.NN.N..~N.ND..$N.DN.MMMMMM
MMMMMM   NN.NN  .NNN NN.NN.:DN N.N.NN N.N.N.N NN.D.NNMMMMMMM
MMMMMM.  NN.NN+..N.N.N$7NN..DN 7.N.NN N..NN..NNN .IN.MMMMMMM
MMMMMMM  NN.NN...N.N.N.NNN..IN N.N.NN NNZ.N.D.NNN NDMMMMMMMM
MMMMMMMZ NN.NN..,N:N:N.NZN. IN N.N.=N.N.N.N.N.+NN N MMMMMMMM
MMMMMMMM ....................NDNNNNNDNNNDNNNNNNNND.MMMMMMMMM
MMMMMMMMM....................?NNNNNNNNNNNNNNNNNNN.MMMMMMMMMM
MMMMMMMMMMM                  .NNNNNNNNNNNNNNNNNN.MMMMMMMMMMM
MMMMMMMMMMMM                  =NNNNNNNNNNNNNNN.MMMMMMMMMMMMM
MMMMMMMMMMMMMM                 ZNNNNNNNNNNNNO?MMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM                NNNNNNNNNN.7MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM$              ZNNNNN..NMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMM$          ....MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

*/
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
